(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Rational.SpecViaQ.QSig.
Require Import ExtLib.QArith.QArith ExtLib.QArith.Qpower ExtLib.QArith.Qminmax ExtLib.Structures.Orders ExtLib.Classes.RelationPairs ExtLib.Structures.GenericMinMax.
(* End Autogenerated Skeleton *)
