(* Autogenerated Skeleton *)
Require Export Coq.Init.Specif.
Require Import ExtLib.Init.Notations.
Require Import ExtLib.Init.Datatypes.
Require Import ExtLib.Init.Logic.
(* End Autogenerated Skeleton *)
