(* Autogenerated Skeleton *)
Require Export Coq.Init.Tactics.
Require Import ExtLib.Init.Notations.
Require Import ExtLib.Init.Logic.
Require Import ExtLib.Init.Specif.
(* End Autogenerated Skeleton *)
