(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.SpecViaZ.NSigNAxioms.
Require Import ExtLib.ZArith.ZArith ExtLib.NArith.Nnat ExtLib.NArith.Ndigits ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NDiv ExtLib.Numbers.Natural.SpecViaZ.NSig.
(* End Autogenerated Skeleton *)
