(* Autogenerated Skeleton *)
Require Export Coq.Wellfounded.Lexicographic_Product.
Require Import ExtLib.Logic.Eqdep.
Require Import ExtLib.Relations.Relation_Operators.
Require Import ExtLib.Wellfounded.Transitive_Closure.
(* End Autogenerated Skeleton *)
