(* Autogenerated Skeleton *)
Require Export Coq.Wellfounded.Lexicographic_Exponentiation.
Require Import ExtLib.Lists.List.
Require Import ExtLib.Relations.Relation_Operators.
Require Import ExtLib.Wellfounded.Transitive_Closure.
(* End Autogenerated Skeleton *)
