(* Autogenerated Skeleton *)
Require Export Coq.Wellfounded.Transitive_Closure.
Require Import ExtLib.Relations.Relation_Definitions.
Require Import ExtLib.Relations.Relation_Operators.
(* End Autogenerated Skeleton *)
