(* Autogenerated Skeleton *)
Require Export Coq.Wellfounded.Union.
Require Import ExtLib.Relations.Relation_Operators.
Require Import ExtLib.Relations.Relation_Definitions.
Require Import ExtLib.Wellfounded.Transitive_Closure.
(* End Autogenerated Skeleton *)
