(* Autogenerated Skeleton *)
Require Export Coq.Wellfounded.Wellfounded.
Require Export ExtLib.Wellfounded.Disjoint_Union.
Require Export ExtLib.Wellfounded.Inclusion.
Require Export ExtLib.Wellfounded.Inverse_Image.
Require Export ExtLib.Wellfounded.Lexicographic_Exponentiation.
Require Export ExtLib.Wellfounded.Lexicographic_Product.
Require Export ExtLib.Wellfounded.Transitive_Closure.
Require Export ExtLib.Wellfounded.Union.
Require Export ExtLib.Wellfounded.Well_Ordering.
(* End Autogenerated Skeleton *)
