(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Cyclic.ZModulo.ZModulo.
Require Import ExtLib.Bool.Bool.
Require Import ExtLib.ZArith.ZArith.
Require Import ExtLib.ZArith.Znumtheory.
Require Import ExtLib.Numbers.BigNumPrelude.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleType.
Require Import ExtLib.Numbers.Cyclic.Abstract.CyclicAxioms.
(* End Autogenerated Skeleton *)
