(* Autogenerated Skeleton *)
Require Export Coq.Structures.DecidableTypeEx.
Require Import ExtLib.Structures.DecidableType ExtLib.Structures.OrderedType ExtLib.Structures.OrderedTypeEx.
(* End Autogenerated Skeleton *)
