(* Autogenerated Skeleton *)
Require Export Coq.Structures.GenericMinMax.
Require Import ExtLib.Structures.Orders ExtLib.Structures.OrdersTac ExtLib.Structures.OrdersFacts ExtLib.Setoids.Setoid ExtLib.Classes.Morphisms ExtLib.Program.Basics.
(* End Autogenerated Skeleton *)
