(* Autogenerated Skeleton *)
Require Export Coq.Structures.OrdersTac.
Require Import ExtLib.Setoids.Setoid ExtLib.Classes.Morphisms ExtLib.Program.Basics ExtLib.Structures.Equalities ExtLib.Structures.Orders.
(* End Autogenerated Skeleton *)
