(* Autogenerated Skeleton *)
Require Export Coq.Structures.OrdersEx.
Require Import ExtLib.Structures.Orders ExtLib.Numbers.Natural.Peano.NPeano ExtLib.PArith.POrderedType ExtLib.NArith.NArith ExtLib.ZArith.ZArith ExtLib.Classes.RelationPairs ExtLib.Structures.EqualitiesFacts.
(* End Autogenerated Skeleton *)
