(* Autogenerated Skeleton *)
Require Export Coq.Structures.OrdersFacts.
Require Import ExtLib.Program.Basics ExtLib.Structures.OrdersTac.
Require Export ExtLib.Structures.Orders.
(* End Autogenerated Skeleton *)
