(* Autogenerated Skeleton *)
Require Export Coq.Structures.OrderedTypeEx.
Require Import ExtLib.Structures.OrderedType.
Require Import ExtLib.ZArith.ZArith.
Require Import Coq.omega.Omega.
Require Import ExtLib.NArith.NArith ExtLib.NArith.Ndec.
Require Import ExtLib.Arith.Compare_dec.
(* End Autogenerated Skeleton *)
