(* Autogenerated Skeleton *)
Require Export Coq.Structures.OrdersEx.
Require Import ExtLib.Structures.Orders NatOrderedType ExtLib.PArith.POrderedType NOrderedType ZOrderedType ExtLib.Classes.RelationPairs ExtLib.Structures.EqualitiesFacts.
(* End Autogenerated Skeleton *)
