(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Binary.ZBinary.
Require Import ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZProperties.
Require Import ExtLib.ZArith.ZArith_base.
(* End Autogenerated Skeleton *)
