(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Binary.ZBinary.
Require Import ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZProperties ExtLib.ZArith.BinInt ExtLib.ZArith.Zcompare ExtLib.ZArith.Zorder ExtLib.ZArith.ZArith_dec ExtLib.ZArith.Zbool ExtLib.ZArith.Zeven ExtLib.ZArith.Zsqrt_def ExtLib.ZArith.Zpow_def ExtLib.ZArith.Zlog_def ExtLib.ZArith.Zgcd_def ExtLib.ZArith.Zdiv_def ExtLib.ZArith.Zdigits_def.
(* End Autogenerated Skeleton *)
