(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.BigN.BigN.
Require Export ExtLib.Numbers.Cyclic.Int31.Int31.
Require Import ExtLib.Numbers.Cyclic.Abstract.CyclicAxioms ExtLib.Numbers.Cyclic.Int31.Cyclic31 ExtLib.Numbers.Cyclic.Int31.Ring31 ExtLib.Numbers.Natural.SpecViaZ.NSig ExtLib.Numbers.Natural.SpecViaZ.NSigNAxioms ExtLib.Numbers.Natural.BigN.NMake ExtLib.Numbers.Natural.Abstract.NProperties ExtLib.Numbers.Natural.Abstract.NDiv ExtLib.Structures.GenericMinMax.
(* End Autogenerated Skeleton *)
