(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.BigN.Nbasic.
Require Import ExtLib.ZArith.ZArith.
Require Import ExtLib.Numbers.BigNumPrelude.
Require Import ExtLib.Arith.Max.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleType.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleBase.
Require Import ExtLib.Numbers.Cyclic.Abstract.CyclicAxioms.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleCyclic.
(* End Autogenerated Skeleton *)
