(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.BigN.NMake.
Require Import ExtLib.Bool.Bool ExtLib.Numbers.BigNumPrelude ExtLib.ZArith.ZArith ExtLib.NArith.Nnat ExtLib.NArith.Ndigits ExtLib.Numbers.Cyclic.Abstract.CyclicAxioms ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleType ExtLib.Numbers.Natural.BigN.Nbasic ExtLib.Arith.Wf_nat ExtLib.Lists.StreamMemo ExtLib.Numbers.Natural.SpecViaZ.NSig ExtLib.Numbers.Natural.BigN.NMake_gen.
(* End Autogenerated Skeleton *)
