(* Autogenerated Skeleton *)
Require Export Coq.PArith.PArith.
Require Export ExtLib.PArith.BinPos ExtLib.PArith.Pnat ExtLib.PArith.Pminmax ExtLib.PArith.Psqrt ExtLib.PArith.Pgcd ExtLib.PArith.POrderedType.
(* End Autogenerated Skeleton *)
