(* Autogenerated Skeleton *)
Require Export Coq.PArith.Pnat.
Require Import ExtLib.PArith.BinPos ExtLib.Arith.Le ExtLib.Arith.Lt ExtLib.Arith.Gt ExtLib.Arith.Plus ExtLib.Arith.Mult ExtLib.Arith.Minus ExtLib.Arith.Compare_dec ExtLib.Arith.Wf_nat.
(* End Autogenerated Skeleton *)
