(* Autogenerated Skeleton *)
Require Export Coq.NArith.NArith.
Require Export ExtLib.PArith.BinPos.
Require Export ExtLib.NArith.BinNat.
Require Export ExtLib.NArith.Nnat.
Require Export ExtLib.NArith.Ndiv_def.
Require Export ExtLib.NArith.Nsqrt_def.
Require Export ExtLib.NArith.Ngcd_def.
Require Export ExtLib.NArith.Ndigits.
Require Export Coq.setoid_ring.NArithRing.
(* End Autogenerated Skeleton *)
