(* Autogenerated Skeleton *)
Require Export Coq.NArith.Ndec.
Require Import ExtLib.Bool.Bool.
Require Import ExtLib.Bool.Sumbool.
Require Import ExtLib.Arith.Arith.
Require Import ExtLib.PArith.BinPos.
Require Import ExtLib.NArith.BinNat.
Require Import ExtLib.PArith.Pnat.
Require Import ExtLib.NArith.Nnat.
Require Import ExtLib.NArith.Ndigits.
(* End Autogenerated Skeleton *)
