(* Autogenerated Skeleton *)
Require Export Coq.NArith.Ndigits.
Require Import ExtLib.Bool.Bool ExtLib.Classes.Morphisms ExtLib.Setoids.Setoid ExtLib.Bool.Bvector ExtLib.PArith.BinPos ExtLib.NArith.BinNat ExtLib.Arith.Wf_nat ExtLib.PArith.Pnat ExtLib.NArith.Nnat ExtLib.NArith.Ndiv_def ExtLib.Arith.Compare_dec ExtLib.Arith.Lt ExtLib.Arith.Minus.
(* End Autogenerated Skeleton *)
