(* Autogenerated Skeleton *)
Require Export Coq.NArith.Ndigits.
Require Import ExtLib.Bool.Bool.
Require Import ExtLib.Bool.Bvector.
Require Import ExtLib.PArith.BinPos.
Require Import ExtLib.NArith.BinNat.
(* End Autogenerated Skeleton *)
