(* Autogenerated Skeleton *)
Require Export Coq.NArith.Nminmax.
Require Import ExtLib.Structures.Orders ExtLib.NArith.BinNat ExtLib.NArith.Nnat NOrderedType ExtLib.Structures.GenericMinMax.
(* End Autogenerated Skeleton *)
