(* Autogenerated Skeleton *)
Require Export Coq.NArith.Nnat.
Require Import ExtLib.Arith.Arith_base ExtLib.Arith.Compare_dec ExtLib.Bool.Sumbool ExtLib.Arith.Div2 ExtLib.Arith.Min ExtLib.Arith.Max.
Require Import ExtLib.PArith.BinPos ExtLib.NArith.BinNat ExtLib.PArith.Pnat.
(* End Autogenerated Skeleton *)
