(* Autogenerated Skeleton *)
Require Export Coq.NArith.NOrderedType.
Require Import ExtLib.NArith.BinNat ExtLib.Structures.Equalities ExtLib.Structures.Orders ExtLib.Structures.OrdersTac.
(* End Autogenerated Skeleton *)
