(* Autogenerated Skeleton *)
Require Export Coq.NArith.Pminmax.
Require Import ExtLib.Structures.Orders ExtLib.PArith.BinPos ExtLib.PArith.Pnat ExtLib.PArith.POrderedType ExtLib.Structures.GenericMinMax.
(* End Autogenerated Skeleton *)
