(* Autogenerated Skeleton *)
Require Export Coq.NArith.Pnat.
Require Import ExtLib.PArith.BinPos.
Require Import ExtLib.Arith.Le.
Require Import ExtLib.Arith.Lt.
Require Import ExtLib.Arith.Gt.
Require Import ExtLib.Arith.Plus.
Require Import ExtLib.Arith.Mult.
Require Import ExtLib.Arith.Minus.
Require Import ExtLib.Arith.Compare_dec.
(* End Autogenerated Skeleton *)
