(* Autogenerated Skeleton *)
Require Export Coq.NArith.POrderedType.
Require Import ExtLib.PArith.BinPos ExtLib.Structures.Equalities ExtLib.Structures.Orders ExtLib.Structures.OrdersTac.
(* End Autogenerated Skeleton *)
