(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Cyclic.Abstract.NZCyclic.
Require Export ExtLib.Numbers.NatInt.NZAxioms.
Require Import ExtLib.Numbers.BigNumPrelude.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleType.
Require Import ExtLib.Numbers.Cyclic.Abstract.CyclicAxioms.
(* End Autogenerated Skeleton *)
