(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZAxioms.
Require Export ExtLib.Numbers.NatInt.NZAxioms.
Require Import ExtLib.Bool.Bool ExtLib.Numbers.NatInt.NZParity ExtLib.Numbers.NatInt.NZPow ExtLib.Numbers.NatInt.NZSqrt ExtLib.Numbers.NatInt.NZLog ExtLib.Numbers.NatInt.NZGcd ExtLib.Numbers.NatInt.NZDiv ExtLib.Numbers.NatInt.NZBits.
(* End Autogenerated Skeleton *)
