(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZBase.
Require Export ExtLib.Logic.Decidable.
Require Export ExtLib.Numbers.Integer.Abstract.ZAxioms.
Require Import ExtLib.Numbers.NatInt.NZProperties.
(* End Autogenerated Skeleton *)
