(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZBits.
Require Import ExtLib.Bool.Bool ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZMulOrder ExtLib.Numbers.Integer.Abstract.ZPow ExtLib.Numbers.Integer.Abstract.ZDivFloor ExtLib.Numbers.Integer.Abstract.ZSgnAbs ExtLib.Numbers.Integer.Abstract.ZParity ExtLib.Numbers.NatInt.NZLog.
(* End Autogenerated Skeleton *)
