(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZDivFloor.
Require Import ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZMulOrder ExtLib.Numbers.Integer.Abstract.ZSgnAbs ExtLib.Numbers.NatInt.NZDiv.
(* End Autogenerated Skeleton *)
