(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZDivEucl.
Require Import ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZProperties ExtLib.Numbers.NatInt.NZDiv.
(* End Autogenerated Skeleton *)
