(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZGcd.
Require Import ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZMulOrder ExtLib.Numbers.Integer.Abstract.ZSgnAbs ExtLib.Numbers.NatInt.NZGcd.
(* End Autogenerated Skeleton *)
