(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZLcm.
Require Import ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZMulOrder ExtLib.Numbers.Integer.Abstract.ZSgnAbs ExtLib.Numbers.Integer.Abstract.ZGcd ExtLib.Numbers.Integer.Abstract.ZDivTrunc ExtLib.Numbers.Integer.Abstract.ZDivFloor.
(* End Autogenerated Skeleton *)
