(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZMaxMin.
Require Import ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZMulOrder ExtLib.Structures.GenericMinMax.
(* End Autogenerated Skeleton *)
