(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZParity.
Require Import ExtLib.Bool.Bool ExtLib.Numbers.Integer.Abstract.ZMulOrder ExtLib.Numbers.NatInt.NZParity.
(* End Autogenerated Skeleton *)
