(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZPow.
Require Import ExtLib.Bool.Bool ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZMulOrder ExtLib.Numbers.Integer.Abstract.ZParity ExtLib.Numbers.Integer.Abstract.ZSgnAbs ExtLib.Numbers.NatInt.NZPow.
(* End Autogenerated Skeleton *)
