(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZProperties.
Require Export ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZMaxMin ExtLib.Numbers.Integer.Abstract.ZSgnAbs ExtLib.Numbers.Integer.Abstract.ZParity ExtLib.Numbers.Integer.Abstract.ZPow ExtLib.Numbers.Integer.Abstract.ZDivTrunc ExtLib.Numbers.Integer.Abstract.ZDivFloor ExtLib.Numbers.Integer.Abstract.ZGcd ExtLib.Numbers.Integer.Abstract.ZLcm ExtLib.Numbers.NatInt.NZLog ExtLib.Numbers.NatInt.NZSqrt ExtLib.Numbers.Integer.Abstract.ZBits.
(* End Autogenerated Skeleton *)
