(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.Abstract.ZProperties.
Require Export ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZMulOrder ExtLib.Numbers.Integer.Abstract.ZSgnAbs.
(* End Autogenerated Skeleton *)
