(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Rational.BigQ.BigQ.
Require Export ExtLib.Numbers.Integer.BigZ.BigZ.
Require Import Coq.setoid_ring.Field ExtLib.QArith.Qfield ExtLib.Numbers.Rational.SpecViaQ.QSig ExtLib.Numbers.Rational.BigQ.QMake ExtLib.Structures.Orders ExtLib.Structures.GenericMinMax.
(* End Autogenerated Skeleton *)
