(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Rational.BigQ.QMake.
Require Import ExtLib.Numbers.BigNumPrelude Coq.romega.ROmega.
Require Import ExtLib.QArith.QArith ExtLib.QArith.Qcanon ExtLib.QArith.Qpower ExtLib.QArith.Qminmax.
Require Import ExtLib.Numbers.Natural.SpecViaZ.NSig ExtLib.Numbers.Integer.SpecViaZ.ZSig ExtLib.Numbers.Rational.SpecViaQ.QSig.
(* End Autogenerated Skeleton *)
