(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Peano.NPeano.
Require Import ExtLib.Arith.Arith MinMax ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NProperties.
Require Import ExtLib.Numbers.Natural.Abstract.NDiv.
(* End Autogenerated Skeleton *)
