(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Peano.NPeano.
Require Import ExtLib.Bool.Bool ExtLib.Init.Peano ExtLib.Arith.Peano_dec ExtLib.Arith.Compare_dec ExtLib.Arith.Plus ExtLib.Arith.Mult ExtLib.Arith.Minus ExtLib.Arith.Le ExtLib.Arith.Lt ExtLib.Arith.EqNat ExtLib.Arith.Div2 ExtLib.Arith.Wf_nat ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NProperties.
(* End Autogenerated Skeleton *)
