(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NAxioms.
Require Export ExtLib.Bool.Bool ExtLib.Numbers.NatInt.NZAxioms ExtLib.Numbers.NatInt.NZParity ExtLib.Numbers.NatInt.NZPow ExtLib.Numbers.NatInt.NZSqrt ExtLib.Numbers.NatInt.NZLog ExtLib.Numbers.NatInt.NZDiv ExtLib.Numbers.NatInt.NZGcd ExtLib.Numbers.NatInt.NZBits.
(* End Autogenerated Skeleton *)
