(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NBase.
Require Export ExtLib.Logic.Decidable.
Require Export ExtLib.Numbers.Natural.Abstract.NAxioms.
Require Import ExtLib.Numbers.NatInt.NZProperties.
(* End Autogenerated Skeleton *)
