(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NBits.
Require Import ExtLib.Bool.Bool ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NSub ExtLib.Numbers.Natural.Abstract.NPow ExtLib.Numbers.Natural.Abstract.NDiv ExtLib.Numbers.Natural.Abstract.NParity ExtLib.Numbers.Natural.Abstract.NLog.
(* End Autogenerated Skeleton *)
