(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NDefOps.
Require Import ExtLib.Bool.Bool.
Require Import ExtLib.Classes.RelationPairs.
Require Export ExtLib.Numbers.Natural.Abstract.NStrongRec.
(* End Autogenerated Skeleton *)
