(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NDiv.
Require Import ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NSub ExtLib.Numbers.NatInt.NZDiv.
(* End Autogenerated Skeleton *)
