(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NGcd.
Require Import ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NSub ExtLib.Numbers.NatInt.NZGcd.
(* End Autogenerated Skeleton *)
