(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NLcm.
Require Import ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NSub ExtLib.Numbers.Natural.Abstract.NDiv ExtLib.Numbers.Natural.Abstract.NGcd.
(* End Autogenerated Skeleton *)
