(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NLog.
Require Import ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NSub ExtLib.Numbers.Natural.Abstract.NPow ExtLib.Numbers.Natural.Abstract.NParity ExtLib.Numbers.NatInt.NZLog.
(* End Autogenerated Skeleton *)
