(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NMaxMin.
Require Import ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NSub ExtLib.Structures.GenericMinMax.
(* End Autogenerated Skeleton *)
