(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NParity.
Require Import ExtLib.Bool.Bool ExtLib.Numbers.Natural.Abstract.NSub ExtLib.Numbers.NatInt.NZParity.
(* End Autogenerated Skeleton *)
