(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NPow.
Require Import ExtLib.Bool.Bool ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NSub ExtLib.Numbers.Natural.Abstract.NParity ExtLib.Numbers.NatInt.NZPow.
(* End Autogenerated Skeleton *)
