(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NProperties.
Require Export ExtLib.Numbers.Natural.Abstract.NAxioms.
Require Import ExtLib.Numbers.Natural.Abstract.NMaxMin ExtLib.Numbers.Natural.Abstract.NParity ExtLib.Numbers.Natural.Abstract.NPow ExtLib.Numbers.Natural.Abstract.NSqrt ExtLib.Numbers.Natural.Abstract.NLog ExtLib.Numbers.Natural.Abstract.NDiv ExtLib.Numbers.Natural.Abstract.NGcd ExtLib.Numbers.Natural.Abstract.NLcm ExtLib.Numbers.Natural.Abstract.NBits.
(* End Autogenerated Skeleton *)
