(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NProperties.
Require Export ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NSub.
(* End Autogenerated Skeleton *)
