(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Abstract.NSqrt.
Require Import ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NSub ExtLib.Numbers.NatInt.NZSqrt.
(* End Autogenerated Skeleton *)
