(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.BigZ.BigZ.
Require Export ExtLib.Numbers.Natural.BigN.BigN.
Require Import ExtLib.Numbers.Integer.Abstract.ZProperties ExtLib.Numbers.Integer.Abstract.ZDivFloor ExtLib.Numbers.Integer.SpecViaZ.ZSig ExtLib.Numbers.Integer.SpecViaZ.ZSigZAxioms ExtLib.Numbers.Integer.BigZ.ZMake.
(* End Autogenerated Skeleton *)
