(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.BigZ.ZMake.
Require Import ExtLib.ZArith.ZArith ExtLib.ZArith.Zquot.
Require Import ExtLib.Numbers.BigNumPrelude.
Require Import ExtLib.Numbers.Natural.SpecViaZ.NSig.
Require Import ExtLib.Numbers.Integer.SpecViaZ.ZSig.
(* End Autogenerated Skeleton *)
