(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Cyclic.DoubleCyclic.DoubleCyclic.
Require Import ExtLib.ZArith.ZArith.
Require Import ExtLib.Numbers.BigNumPrelude.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleType.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleBase.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleAdd.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleSub.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleMul.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleSqrt.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleLift.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleDivn1.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleDiv.
Require Import ExtLib.Numbers.Cyclic.Abstract.CyclicAxioms.
(* End Autogenerated Skeleton *)
