(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Cyclic.DoubleCyclic.DoubleDiv.
Require Import ExtLib.ZArith.ZArith.
Require Import ExtLib.Numbers.BigNumPrelude.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleType.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleBase.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleDivn1.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleAdd.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleSub.
(* End Autogenerated Skeleton *)
