(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Cyclic.DoubleCyclic.DoubleBase.
Require Import ExtLib.ZArith.ZArith.
Require Import ExtLib.Numbers.BigNumPrelude.
Require Import ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleType.
(* End Autogenerated Skeleton *)
