(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.NatPairs.ZNatPairs.
Require Import ExtLib.Numbers.Natural.Abstract.NProperties.
Require Export ExtLib.Numbers.Integer.Abstract.ZProperties.
Require Export Coq.setoid_ring.Ring.
(* End Autogenerated Skeleton *)
