(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.NatPairs.ZNatPairs.
Require Import ExtLib.Numbers.Natural.Abstract.NSub ExtLib.Numbers.Integer.Abstract.ZAxioms.
Require Export Coq.setoid_ring.Ring.
(* End Autogenerated Skeleton *)
