(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Cyclic.Int31.Int31.
Require Import ExtLib.Numbers.NaryFunctions.
Require Import ExtLib.Arith.Wf_nat.
Require Export ExtLib.ZArith.ZArith.
Require Export ExtLib.Numbers.Cyclic.DoubleCyclic.DoubleType.
(* End Autogenerated Skeleton *)
