(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Cyclic.Int31.Ring31.
Require Import ExtLib.Numbers.Cyclic.Int31.Int31 ExtLib.Numbers.Cyclic.Int31.Cyclic31 ExtLib.Numbers.Cyclic.Abstract.CyclicAxioms.
(* End Autogenerated Skeleton *)
