(* Autogenerated Skeleton *)
Require Export Coq.Classes.SetoidDec.
Require Export ExtLib.Classes.SetoidClass.
Require Import ExtLib.Logic.Decidable.
Require Import ExtLib.Program.Program.
Require Import ExtLib.Arith.Arith.
Require Import ExtLib.Bool.Bool.
(* End Autogenerated Skeleton *)
