(* Autogenerated Skeleton *)
Require Export Coq.Classes.SetoidTactics.
Require Import ExtLib.Classes.Morphisms ExtLib.Classes.Morphisms_Prop.
Require Export ExtLib.Classes.RelationClasses ExtLib.Relations.Relation_Definitions.
Require Import ExtLib.Classes.Equivalence ExtLib.Program.Basics.
Require Import ExtLib.Program.Tactics.
(* End Autogenerated Skeleton *)
