(* Autogenerated Skeleton *)
Require Export Coq.Classes.SetoidClass.
Require Import ExtLib.Program.Program.
Require Import ExtLib.Relations.Relation_Definitions.
Require Export ExtLib.Classes.RelationClasses.
Require Export ExtLib.Classes.Morphisms.
(* End Autogenerated Skeleton *)
