(* Autogenerated Skeleton *)
Require Export Coq.MSets.MSetToFiniteSet.
Require Import ExtLib.Sets.Ensembles ExtLib.Sets.Finite_sets.
Require Import ExtLib.MSets.MSetInterface ExtLib.MSets.MSetProperties ExtLib.Structures.OrdersEx.
(* End Autogenerated Skeleton *)
