(* Autogenerated Skeleton *)
Require Export Coq.Relations.Operators_Properties.
Require Import ExtLib.Relations.Relation_Definitions.
Require Import ExtLib.Relations.Relation_Operators.
(* End Autogenerated Skeleton *)
