(* Autogenerated Skeleton *)
Require Export Coq.Numbers.NatInt.NZAddOrder.
Require Import ExtLib.Numbers.NatInt.NZAxioms ExtLib.Numbers.NatInt.NZBase ExtLib.Numbers.NatInt.NZMul ExtLib.Numbers.NatInt.NZOrder.
(* End Autogenerated Skeleton *)
