(* Autogenerated Skeleton *)
Require Export Coq.Numbers.NatInt.NZAxioms.
Require Export ExtLib.Structures.Equalities ExtLib.Structures.Orders ExtLib.Numbers.NumPrelude ExtLib.Structures.GenericMinMax.
(* End Autogenerated Skeleton *)
