(* Autogenerated Skeleton *)
Require Export Coq.Numbers.NatInt.NZBits.
Require Import ExtLib.Bool.Bool ExtLib.Numbers.NatInt.NZAxioms ExtLib.Numbers.NatInt.NZMulOrder ExtLib.Numbers.NatInt.NZParity ExtLib.Numbers.NatInt.NZPow ExtLib.Numbers.NatInt.NZDiv ExtLib.Numbers.NatInt.NZLog.
(* End Autogenerated Skeleton *)
