(* Autogenerated Skeleton *)
Require Export Coq.Numbers.NatInt.NZDomain.
Require Export ExtLib.Numbers.NumPrelude ExtLib.Numbers.NatInt.NZAxioms.
Require Import ExtLib.Numbers.NatInt.NZBase ExtLib.Numbers.NatInt.NZOrder ExtLib.Numbers.NatInt.NZAddOrder ExtLib.Arith.Plus ExtLib.Arith.Minus.
(* End Autogenerated Skeleton *)
