(* Autogenerated Skeleton *)
Require Export Coq.Numbers.NatInt.NZLog.
Require Import ExtLib.Numbers.NatInt.NZAxioms ExtLib.Numbers.NatInt.NZMulOrder ExtLib.Numbers.NatInt.NZPow.
(* End Autogenerated Skeleton *)
