(* Autogenerated Skeleton *)
Require Export Coq.Numbers.NatInt.NZMulOrder.
Require Import ExtLib.Numbers.NatInt.NZAxioms.
Require Import ExtLib.Numbers.NatInt.NZAddOrder.
(* End Autogenerated Skeleton *)
