(* Autogenerated Skeleton *)
Require Export Coq.Numbers.NatInt.NZMul.
Require Import ExtLib.Numbers.NatInt.NZAxioms ExtLib.Numbers.NatInt.NZBase ExtLib.Numbers.NatInt.NZAdd.
(* End Autogenerated Skeleton *)
