(* Autogenerated Skeleton *)
Require Export Coq.Numbers.NatInt.NZOrder.
Require Import ExtLib.Numbers.NatInt.NZAxioms ExtLib.Numbers.NatInt.NZBase ExtLib.Logic.Decidable ExtLib.Structures.OrdersTac.
(* End Autogenerated Skeleton *)
