(* Autogenerated Skeleton *)
Require Export Coq.Numbers.NatInt.NZParity.
Require Import ExtLib.Bool.Bool ExtLib.Numbers.NatInt.NZAxioms ExtLib.Numbers.NatInt.NZMulOrder.
(* End Autogenerated Skeleton *)
