(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Binary.NBinary.
Require Import ExtLib.PArith.BinPos ExtLib.NArith.Ndiv_def ExtLib.NArith.Nsqrt_def ExtLib.NArith.Ngcd_def ExtLib.NArith.Ndigits.
Require Export ExtLib.NArith.BinNat.
Require Import ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NProperties.
(* End Autogenerated Skeleton *)
