(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Natural.Binary.NBinary.
Require Import ExtLib.PArith.BinPos.
Require Export ExtLib.NArith.BinNat.
Require Import ExtLib.Numbers.Natural.Abstract.NAxioms ExtLib.Numbers.Natural.Abstract.NProperties.
(* End Autogenerated Skeleton *)
