(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.SpecViaZ.ZSigZAxioms.
Require Import ExtLib.Bool.Bool ExtLib.ZArith.ZArith ExtLib.NArith.Nnat ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.SpecViaZ.ZSig.
(* End Autogenerated Skeleton *)
