(* Autogenerated Skeleton *)
Require Export Coq.Numbers.Integer.SpecViaZ.ZSigZAxioms.
Require Import ExtLib.ZArith.ZArith ExtLib.Numbers.Integer.Abstract.ZAxioms ExtLib.Numbers.Integer.Abstract.ZDivFloor ExtLib.Numbers.Integer.SpecViaZ.ZSig.
(* End Autogenerated Skeleton *)
