(* Autogenerated Skeleton *)
Require Export Coq.ZArith.auxiliary.
Require Export ExtLib.Arith.Arith_base.
Require Import ExtLib.ZArith.BinInt.
Require Import ExtLib.ZArith.Zorder.
Require Import ExtLib.Logic.Decidable.
Require Import ExtLib.Arith.Peano_dec.
Require Export ExtLib.Arith.Compare_dec.
(* End Autogenerated Skeleton *)
