(* Autogenerated Skeleton *)
Require Export Coq.ZArith.BinInt.
Require Export ExtLib.PArith.BinPos.
Require Export ExtLib.PArith.Pnat.
Require Import ExtLib.NArith.BinNat.
Require Import ExtLib.Arith.Plus.
Require Import ExtLib.Arith.Mult.
Require Import ExtLib.NArith.BinNat.
(* End Autogenerated Skeleton *)
