(* Autogenerated Skeleton *)
Require Export Coq.ZArith.BinInt.
Require Export ExtLib.PArith.BinPos ExtLib.PArith.Pnat.
Require Import ExtLib.NArith.BinNat ExtLib.Arith.Plus ExtLib.Arith.Mult.
(* End Autogenerated Skeleton *)
