(* Autogenerated Skeleton *)
Require Export Coq.ZArith.ZArith.
Require Export ExtLib.ZArith.ZArith_base.
Require Export ExtLib.ZArith.Zpow_def ExtLib.ZArith.Zsqrt_def ExtLib.ZArith.Zlog_def ExtLib.ZArith.Zgcd_def ExtLib.ZArith.Zdiv_def ExtLib.ZArith.Zdigits_def.
Require Export ExtLib.ZArith.Zcomplements.
Require Export ExtLib.ZArith.Zpower.
Require Export ExtLib.ZArith.Zdiv.
Require Export ExtLib.ZArith.Zlogarithm.
(* End Autogenerated Skeleton *)
