(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Zcompare.
Require Export ExtLib.PArith.BinPos.
Require Export ExtLib.ZArith.BinInt.
Require Import ExtLib.Arith.Lt.
Require Import ExtLib.Arith.Gt.
Require Import ExtLib.Arith.Plus.
Require Import ExtLib.Arith.Mult.
(* End Autogenerated Skeleton *)
