(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Zcompare.
Require Export ExtLib.PArith.BinPos ExtLib.ZArith.BinInt.
Require Import ExtLib.Arith.Lt ExtLib.Arith.Gt ExtLib.Arith.Plus ExtLib.Arith.Mult.
(* End Autogenerated Skeleton *)
