(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Zdigits_def.
Require Import ExtLib.Bool.Bool ExtLib.PArith.BinPos ExtLib.NArith.BinNat ExtLib.ZArith.BinInt ExtLib.NArith.Ndigits ExtLib.ZArith.Znat ExtLib.ZArith.Zeven ExtLib.ZArith.Zpow_def ExtLib.ZArith.Zorder ExtLib.ZArith.Zcompare.
(* End Autogenerated Skeleton *)
