(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Zdiv.
Require Export ExtLib.ZArith.ZArith_base ExtLib.ZArith.Zdiv_def.
Require Import ExtLib.ZArith.Zbool Coq.omega.Omega Coq.setoid_ring.ZArithRing ExtLib.ZArith.Zcomplements ExtLib.Setoids.Setoid ExtLib.Classes.Morphisms.
Require Import ExtLib.Numbers.Natural.Peano.NPeano.
(* End Autogenerated Skeleton *)
