(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Zdiv_def.
Require Import ExtLib.PArith.BinPos ExtLib.NArith.BinNat ExtLib.ZArith.BinInt ExtLib.ZArith.Zbool ExtLib.ZArith.Zcompare ExtLib.ZArith.Zorder ExtLib.ZArith.Zabs ExtLib.ZArith.Znat ExtLib.NArith.Ndiv_def.
(* End Autogenerated Skeleton *)
