(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Zeuclid.
Require Import ExtLib.Classes.Morphisms ExtLib.ZArith.BinInt ExtLib.ZArith.Zdiv_def ExtLib.Numbers.Integer.Binary.ZBinary ExtLib.Numbers.Integer.Abstract.ZDivEucl.
(* End Autogenerated Skeleton *)
