(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Zmax.
Require Export ExtLib.ZArith.BinInt ExtLib.ZArith.Zcompare ExtLib.ZArith.Zorder ExtLib.Numbers.Integer.Binary.ZBinary.
(* End Autogenerated Skeleton *)
