(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Zminmax.
Require Import ExtLib.Structures.Orders ExtLib.ZArith.BinInt ExtLib.ZArith.Zcompare ExtLib.ZArith.Zorder ZOrderedType ExtLib.Structures.GenericMinMax.
(* End Autogenerated Skeleton *)
