(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Znat.
Require Export ExtLib.Arith.Arith_base.
Require Import ExtLib.PArith.BinPos.
Require Import ExtLib.ZArith.BinInt.
Require Import ExtLib.ZArith.Zcompare.
Require Import ExtLib.ZArith.Zorder.
Require Import ExtLib.Logic.Decidable.
Require Import ExtLib.Arith.Peano_dec.
Require Import ExtLib.Arith.Min ExtLib.Arith.Max ExtLib.ZArith.Zmin ExtLib.ZArith.Zmax.
Require Export ExtLib.Arith.Compare_dec.
(* End Autogenerated Skeleton *)
