(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Znat.
Require Export ExtLib.Arith.Arith_base.
Require Import ExtLib.PArith.BinPos ExtLib.ZArith.BinInt ExtLib.NArith.BinNat ExtLib.ZArith.Zcompare ExtLib.ZArith.Zorder.
Require Import ExtLib.Logic.Decidable ExtLib.Arith.Peano_dec ExtLib.Arith.Min ExtLib.Arith.Max ExtLib.Arith.Compare_dec.
(* End Autogenerated Skeleton *)
