(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Znumtheory.
Require Import ExtLib.ZArith.ZArith_base.
Require Import Coq.setoid_ring.ZArithRing.
Require Import ExtLib.ZArith.Zcomplements.
Require Import ExtLib.ZArith.Zdiv.
Require Import ExtLib.Arith.Wf_nat.
(* End Autogenerated Skeleton *)
