(* Autogenerated Skeleton *)
Require Export Coq.ZArith.ZOdiv.
Require Import ExtLib.PArith.BinPos ExtLib.NArith.BinNat ExtLib.NArith.Nnat ExtLib.ZArith.ZArith_base Coq.romega.ROmega Coq.setoid_ring.ZArithRing.
Require Export ZOdiv_def.
(* End Autogenerated Skeleton *)
