(* Autogenerated Skeleton *)
Require Export Coq.ZArith.ZOdiv_def.
Require Import ExtLib.PArith.BinPos ExtLib.NArith.BinNat ExtLib.NArith.Nnat ExtLib.ZArith.ZArith_base.
(* End Autogenerated Skeleton *)
