(* Autogenerated Skeleton *)
Require Export Coq.ZArith.ZOrderedType.
Require Import ExtLib.ZArith.BinInt ExtLib.ZArith.Zcompare ExtLib.ZArith.Zorder ExtLib.ZArith.Zbool ExtLib.ZArith.ZArith_dec ExtLib.Structures.Equalities ExtLib.Structures.Orders ExtLib.Structures.OrdersTac.
(* End Autogenerated Skeleton *)
