(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Zpow_facts.
Require Import ExtLib.ZArith.ZArith_base.
Require Import Coq.setoid_ring.ZArithRing.
Require Import ExtLib.ZArith.Zcomplements.
Require Export ExtLib.ZArith.Zpower.
Require Import ExtLib.ZArith.Zdiv.
Require Import ExtLib.ZArith.Znumtheory.
(* End Autogenerated Skeleton *)
