(* Autogenerated Skeleton *)
Require Export Coq.ZArith.Zquot.
Require Import ExtLib.PArith.BinPos ExtLib.NArith.BinNat ExtLib.NArith.Nnat ExtLib.ZArith.ZArith_base Coq.romega.ROmega Coq.setoid_ring.ZArithRing ExtLib.Classes.Morphisms ExtLib.ZArith.Zdiv.
Require Export ExtLib.NArith.Ndiv_def ExtLib.ZArith.Zdiv_def.
(* End Autogenerated Skeleton *)
