(* Autogenerated Skeleton *)
Require Export Coq.Arith.Arith_base.
Require Export ExtLib.Arith.Le.
Require Export ExtLib.Arith.Lt.
Require Export ExtLib.Arith.Plus.
Require Export ExtLib.Arith.Gt.
Require Export ExtLib.Arith.Minus.
Require Export ExtLib.Arith.Mult.
Require Export ExtLib.Arith.Between.
Require Export ExtLib.Arith.Peano_dec.
Require Export ExtLib.Arith.Compare_dec.
Require Export ExtLib.Arith.Factorial.
Require Export ExtLib.Arith.EqNat.
Require Export ExtLib.Arith.Wf_nat.
(* End Autogenerated Skeleton *)
