(* Autogenerated Skeleton *)
Require Export Coq.Arith.Bool_nat.
Require Export ExtLib.Arith.Compare_dec.
Require Export ExtLib.Arith.Peano_dec.
Require Import ExtLib.Bool.Sumbool.
(* End Autogenerated Skeleton *)
