(* Autogenerated Skeleton *)
Require Export Coq.Arith.Compare.
Require Import ExtLib.Arith.Arith_base.
Require Import ExtLib.Arith.Peano_dec.
Require Import ExtLib.Arith.Compare_dec.
Require Export ExtLib.Arith.Wf_nat.
Require Export ExtLib.Arith.Min ExtLib.Arith.Max.
(* End Autogenerated Skeleton *)
