(* Autogenerated Skeleton *)
Require Export Coq.Arith.Euclid.
Require Import ExtLib.Arith.Mult.
Require Import ExtLib.Arith.Compare_dec.
Require Import ExtLib.Arith.Wf_nat.
(* End Autogenerated Skeleton *)
