(* Autogenerated Skeleton *)
Require Export Coq.Arith.Mult.
Require Export ExtLib.Arith.Plus.
Require Export ExtLib.Arith.Minus.
Require Export ExtLib.Arith.Lt.
Require Export ExtLib.Arith.Le.
(* End Autogenerated Skeleton *)
