(* Autogenerated Skeleton *)
Require Export Coq.Arith.NatOrderedType.
Require Import ExtLib.Arith.Lt ExtLib.Arith.Peano_dec ExtLib.Arith.Compare_dec ExtLib.Arith.EqNat ExtLib.Structures.Equalities ExtLib.Structures.Orders ExtLib.Structures.OrdersTac.
(* End Autogenerated Skeleton *)
