(* Autogenerated Skeleton *)
Require Export Coq.Arith.Wf_nat.
Require Import ExtLib.Arith.Lt.
Require Import ExtLib.Arith.Le.
Require Import ExtLib.Arith.Compare_dec.
Require Import ExtLib.Logic.Decidable.
(* End Autogenerated Skeleton *)
