(* Autogenerated Skeleton *)
Require Export Coq.Logic.ChoiceFacts.
Require Import ExtLib.Arith.Wf_nat.
Require Import ExtLib.Logic.Decidable.
Require Import ExtLib.Setoids.Setoid.
Require Import ExtLib.Arith.Arith.
(* End Autogenerated Skeleton *)
