(* Autogenerated Skeleton *)
Require Export Coq.Logic.ClassicalChoice.
Require Export ExtLib.Logic.ClassicalUniqueChoice.
Require Export ExtLib.Logic.RelationalChoice.
Require Import ExtLib.Logic.ChoiceFacts.
(* End Autogenerated Skeleton *)
