(* Autogenerated Skeleton *)
Require Export Coq.Logic.Diaconescu.
Require Import ExtLib.Logic.ClassicalFacts.
Require Import ExtLib.Logic.ChoiceFacts.
Require Import ExtLib.Bool.Bool.
(* End Autogenerated Skeleton *)
