(* Autogenerated Skeleton *)
Require Export Coq.Sorting.Mergesort.
Require Import ExtLib.Lists.List ExtLib.Setoids.Setoid ExtLib.Sorting.Permutation ExtLib.Sorting.Sorted ExtLib.Structures.Orders.
(* End Autogenerated Skeleton *)
