(* Autogenerated Skeleton *)
Require Export Coq.Reals.ArithProp.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.Rbasic_fun.
Require Import ExtLib.Arith.Even.
Require Import ExtLib.Arith.Div2.
Require Import Coq.setoid_ring.ArithRing.
(* End Autogenerated Skeleton *)
