(* Autogenerated Skeleton *)
Require Export Coq.Reals.Cos_rel.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.Rfunctions.
Require Import ExtLib.Reals.SeqSeries.
Require Import ExtLib.Reals.Rtrigo_def.
(* End Autogenerated Skeleton *)
