(* Autogenerated Skeleton *)
Require Export Coq.Reals.NewtonInt.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.Rfunctions.
Require Import ExtLib.Reals.SeqSeries.
Require Import ExtLib.Reals.Rtrigo.
Require Import ExtLib.Reals.Ranalysis.
(* End Autogenerated Skeleton *)
