(* Autogenerated Skeleton *)
Require Export Coq.Reals.PSeries_reg.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.Rfunctions.
Require Import ExtLib.Reals.SeqSeries.
Require Import ExtLib.Reals.Ranalysis1.
Require Import ExtLib.Arith.Max.
Require Import ExtLib.Arith.Even.
(* End Autogenerated Skeleton *)
