(* Autogenerated Skeleton *)
Require Export Coq.Reals.R_sqrt.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.Rfunctions.
Require Import ExtLib.Reals.Rsqrt_def.
(* End Autogenerated Skeleton *)
