(* Autogenerated Skeleton *)
Require Export Coq.Reals.Rbasic_fun.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.R_Ifp.
Require Import Coq.fourier.Fourier.
(* End Autogenerated Skeleton *)
