(* Autogenerated Skeleton *)
Require Export Coq.Reals.Rderiv.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.Rfunctions.
Require Import ExtLib.Reals.Rlimit.
Require Import Coq.fourier.Fourier.
Require Import ExtLib.Logic.Classical_Prop.
Require Import ExtLib.Logic.Classical_Pred_Type.
Require Import Coq.omega.Omega.
(* End Autogenerated Skeleton *)
