(* Autogenerated Skeleton *)
Require Export Coq.Reals.Rfunctions.
Require Export Coq.setoid_ring.ArithRing.
Require Import ExtLib.Reals.Rbase.
Require Export ExtLib.Reals.Rpow_def.
Require Export ExtLib.Reals.R_Ifp.
Require Export ExtLib.Reals.Rbasic_fun.
Require Export ExtLib.Reals.R_sqr.
Require Export ExtLib.Reals.SplitAbsolu.
Require Export ExtLib.Reals.SplitRmult.
Require Export ExtLib.Reals.ArithProp.
Require Import Coq.omega.Omega.
Require Import ExtLib.ZArith.Zpower.
(* End Autogenerated Skeleton *)
