(* Autogenerated Skeleton *)
Require Export Coq.Reals.RIneq.
Require Export ExtLib.Reals.Raxioms.
Require Import ExtLib.Reals.Rpow_def.
Require Import ExtLib.ZArith.Zpower.
Require Export Coq.setoid_ring.ZArithRing.
Require Import Coq.omega.Omega.
Require Export Coq.setoid_ring.RealField.
(* End Autogenerated Skeleton *)
