(* Autogenerated Skeleton *)
Require Export Coq.Reals.Rminmax.
Require Import ExtLib.Structures.Orders ExtLib.Reals.Rbase ExtLib.Reals.Rbasic_fun ExtLib.Reals.ROrderedType ExtLib.Structures.GenericMinMax.
(* End Autogenerated Skeleton *)
