(* Autogenerated Skeleton *)
Require Export Coq.Reals.ROrderedType.
Require Import ExtLib.Reals.Rbase ExtLib.Structures.Equalities ExtLib.Structures.Orders ExtLib.Structures.OrdersTac.
(* End Autogenerated Skeleton *)
