(* Autogenerated Skeleton *)
Require Export Coq.Reals.Rprod.
Require Import ExtLib.Arith.Compare.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.Rfunctions.
Require Import ExtLib.Reals.Rseries.
Require Import ExtLib.Reals.PartSum.
Require Import ExtLib.Reals.Binomial.
(* End Autogenerated Skeleton *)
