(* Autogenerated Skeleton *)
Require Export Coq.Reals.Rseries.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.Rfunctions.
Require Import ExtLib.Arith.Compare.
(* End Autogenerated Skeleton *)
