(* Autogenerated Skeleton *)
Require Export Coq.Reals.Rtrigo.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.Rfunctions.
Require Import ExtLib.Reals.SeqSeries.
Require Export ExtLib.Reals.Rtrigo_fun.
Require Export ExtLib.Reals.Rtrigo_def.
Require Export ExtLib.Reals.Rtrigo_alt.
Require Export ExtLib.Reals.Cos_rel.
Require Export ExtLib.Reals.Cos_plus.
Require Import ExtLib.ZArith.ZArith_base.
Require Import ExtLib.ZArith.Zcomplements.
Require Import ExtLib.Logic.Classical_Prop.
(* End Autogenerated Skeleton *)
