(* Autogenerated Skeleton *)
Require Export Coq.Reals.Rtrigo_fun.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.Rfunctions.
Require Import ExtLib.Reals.SeqSeries.
(* End Autogenerated Skeleton *)
