(* Autogenerated Skeleton *)
Require Export Coq.Reals.Rtrigo_def.
Require Import ExtLib.Reals.Rbase.
Require Import ExtLib.Reals.Rfunctions.
Require Import ExtLib.Reals.SeqSeries.
Require Import ExtLib.Reals.Rtrigo_fun.
Require Import ExtLib.Arith.Max.
(* End Autogenerated Skeleton *)
