(* Autogenerated Skeleton *)
Require Export Coq.Reals.Rtrigo_def.
Require Import ExtLib.Reals.Rbase ExtLib.Reals.Rfunctions ExtLib.Reals.SeqSeries ExtLib.Reals.Rtrigo_fun ExtLib.Arith.Max.
(* End Autogenerated Skeleton *)
