(* Autogenerated Skeleton *)
Require Export Coq.QArith.QArith.
Require Export ExtLib.QArith.QArith_base.
Require Export ExtLib.QArith.Qring.
Require Export ExtLib.QArith.Qreduction.
(* End Autogenerated Skeleton *)
