(* Autogenerated Skeleton *)
Require Export Coq.QArith.QArith_base.
Require Export ExtLib.ZArith.ZArith.
Require Export Coq.setoid_ring.ZArithRing.
Require Export ExtLib.Classes.Morphisms ExtLib.Setoids.Setoid ExtLib.Bool.Bool.
(* End Autogenerated Skeleton *)
