(* Autogenerated Skeleton *)
Require Export Coq.QArith.Qfield.
Require Export Coq.setoid_ring.Field.
Require Export ExtLib.QArith.QArith_base.
Require Import Coq.setoid_ring.NArithRing.
(* End Autogenerated Skeleton *)
