(* Autogenerated Skeleton *)
Require Export Coq.QArith.Qminmax.
Require Import ExtLib.QArith.QArith_base ExtLib.Structures.Orders ExtLib.QArith.QOrderedType ExtLib.Structures.GenericMinMax.
(* End Autogenerated Skeleton *)
