(* Autogenerated Skeleton *)
Require Export Coq.QArith.QOrderedType.
Require Import ExtLib.QArith.QArith_base ExtLib.Structures.Equalities ExtLib.Structures.Orders ExtLib.Structures.OrdersTac.
(* End Autogenerated Skeleton *)
