(* Autogenerated Skeleton *)
Require Export Coq.QArith.Qreduction.
Require Export ExtLib.QArith.QArith_base.
Require Import ExtLib.ZArith.Zgcd_def ExtLib.ZArith.Znumtheory.
(* End Autogenerated Skeleton *)
